name: vocabulary
description: "GSAT 7000 Vocabulary"

version: 0.0.3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  animations: ^2.0.11
  tutorial_coach_mark: ^1.3.0
  flutter_local_notifications: ^19.3.0
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  app_settings: ^5.1.0
  http: ^1.5.0
  crypto: ^3.0.6
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:

  fonts:
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
          weight: 300

  uses-material-design: true
  assets:
    - assets/document/language/
    - assets/document/tutorial/
    - assets/document/

flutter_native_splash:
  color: "#111111"
  image: assets/icon/icon.png
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  web: true
  path: "assets/icon/icon.png"
